name: Sync Preços Manual

on:
  workflow_dispatch:
    inputs:
      limite_itens:
        description: 'Limite de itens (vazio = TODOS)'
        required: false
        type: string
        default: ''
      lote_size:
        description: 'Tamanho do lote'
        required: false
        type: number
        default: 5

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      
      - name: Configurar Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install aiohttp==3.9.1 psycopg2-binary==2.9.9 python-dotenv==1.0.0 pandas==2.1.4 charset-normalizer==3.3.2 ftfy==6.1.3
      
      - name: Criar arquivo de conexão
        run: |
          echo "COCKROACHDB_CONN_STRING=${{ secrets.COCKROACHDB_CONN_STRING }}" > dbconnection.env
      
      - name: Criar pasta de logs
        run: mkdir -p logs
      
      - name: Executar sincronização
        env:
          LIMITE_ITENS: ${{ inputs.limite_itens }}
          LOTE_SIZE: ${{ inputs.lote_size }}
        run: python atualizar_precos_catalogo.py
      
      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-sync-${{ github.run_number }}
          path: logs/*.log
          retention-days: 30
          if-no-files-found: warn
      
      - name: Resumo da execução
        if: always()
        run: |
          echo "## Resumo da Sincronização" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Run Number:** #${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tamanho do Lote:** ${{ inputs.lote_size }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          if [ -f logs/*.log ]; then
            echo "### Últimas 50 linhas do log:" >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          else
            echo "Nenhum arquivo de log foi gerado." >> $GITHUB_STEP_SUMMARY
          fi
